create table if not exists public.wedding_wishes (
  id bigint generated by default as identity primary key,
  name varchar(20) not null,
  wish varchar(120) not null,
  created_at timestamptz not null default now()
);

create index if not exists wedding_wishes_created_at_idx
  on public.wedding_wishes (created_at desc);

create table if not exists public.wedding_photos (
  id bigint generated by default as identity primary key,
  name varchar(20) not null default '亲友',
  file_id text not null,
  cloud_path text not null,
  created_at timestamptz not null default now()
);

create index if not exists wedding_photos_created_at_idx
  on public.wedding_photos (created_at desc);

alter table public.wedding_wishes enable row level security;
alter table public.wedding_photos enable row level security;
